import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: "flex",
        flexFlow: "row nowrap",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
      }}>
        <div style={{
            textAlign: "center",
            // marginTop: "-50px"
        }}>
          <h1 style={{margin: "0 0 24px 0"}}>Synquencer</h1>
          <button className="homeMenuButton">New Sequence</button>
          <button className="homeMenuButton">About</button>
        </div>
      </div>
    </>
  )
}
