import Head from "next/head";
import {
	Instrument,
	instrumentList,
	Note,
	PitchLocation,
	SequenceMetadata,
} from "@/server/types";
import { GetServerSidePropsContext, GetServerSidePropsResult } from "next";
import {
	AddNote,
	AddNotes,
	ClearNotes,
	DeleteNote,
	EditNote,
	EditSequence,
	GetNotes,
	GetSequence,
} from "@/database/calls";
import PianoRoll from "@/components/PianoRoll";
import TopBar from "@/components/TopBar";
import { useEffect, useMemo, useRef, useState } from "react";
import {
	getInstruments,
	getTick,
	PlaySequence,
	setTickFunction,
	StopSequence,
	WriteMidi,
} from "@/client/write_midi";
import Cursor from "@/components/Cursor";
import {
	loadSequence,
	//getContainer,
	sequenceSharedMapToDatabase,
	//sequenceDatabaseToSharedMap,
	getFluidData
} from "../_app";
import { SharedMap, IFluidContainer } from "fluid-framework";

type PageParams = {
	id: string;
};
type ContentPageProps = {
	sequence: SequenceMetadata;
	notes: Array<Note>;
};

export default function Home({ sequence, notes }: ContentPageProps) {
	//const thisInterval = useRef<NodeJS.Timer>();
	//const doReload = useRef<boolean>(true);
	const [tick, setTick] = useState(-1);
	const [updateSeq, setUpdateSeq] = useState(0);

	sequence = new SequenceMetadata(sequence);
	notes = notes.map((note) => {
		return new Note(note);
	});

	
	const [unsharedMap, setUnsharedMap] = useState<Map<string, Note>>(new Map<string, Note>());


	const [seqData, setSeq] = useState(sequence);
	const [currentInstrument, setCurrentInstrument] = useState({
		instrument: instrumentList.Piano,
		primary: "--yellow",
		accent: "--yellow-accent",
	});

	// const sequenceMap = useMemo(() => {
	// 	return getContainer().initialObjects.sequence as SharedMap;
	// }, []);

	function getArray() {
		return Array.from((fluidSequence as SharedMap).values());
		//return sequenceSharedMapToDatabase(sequenceMap);
	}

	const [stepLength, setStepLength] = useState(1);
	const [container, setContainer] = useState<IFluidContainer>();

	const [fluidMetadata, setMetadata] = useState<SharedMap | null>(null);
	//const sequenceState = useState<SharedMap | null>(null);
	//const [fluidSequence, setSequence]: [SharedMap, any] = [sequenceState[0] as SharedMap, sequenceState[1]];
	const [fluidSequence, setSequence] = useState<SharedMap | null>(null);

	useEffect(() => {
		getFluidData().then((data)=> {
			setContainer(data);
			setMetadata(data.initialObjects.metadata as SharedMap);
			setSequence(data.initialObjects.sequence as SharedMap);
		});
	// eslint-disable-next-line react-hooks/exhaustive-deps
	}, []);

	useEffect(() => {
		if (fluidMetadata !== null) {
			const updateLocalMetadata = () => {
				if (fluidMetadata != null) {
					const args = Object.fromEntries(fluidMetadata.entries());
					const clazz = SequenceMetadata as new (arg: any) => any;
					setSeq(new clazz(args));
				}
			};
			updateLocalMetadata();
			fluidMetadata.on("valueChanged", updateLocalMetadata);
			return () => {};
		} else {
			return;
		}
	}, [fluidMetadata]);

	useEffect(() => {
		if (fluidSequence !== null) {
			const updateLocalSequence = () => {
				setSequence(fluidSequence);
				let map: Map<string, Note> = new Map<string, Note>();
				for (let submap of Array.from(fluidSequence.values())) {
					(submap as SharedMap).forEach((note) => map.set(note.serialize(), note));
				}
				setUnsharedMap(map);
			};
			updateLocalSequence();
			fluidSequence.on("valueChanged", updateLocalSequence);
			return () => {};
		} else {
			return;
		}
	}, [fluidSequence, setSequence]);

	useEffect(() => {
		// Render Instruments
		getInstruments();
	}, []);

	useEffect(() => {
		setUpdateSeq(updateSeq + 1);
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [seqData]);

	function addNote(note: Note) {
		let submap: SharedMap = (fluidSequence as SharedMap).get(note.instrument.serialize()) as SharedMap;
		while (fluidSequence == undefined) {}
		if (submap == undefined) {
			(container as IFluidContainer).create(SharedMap).then((data) => {
				while (data == undefined) {}
				submap = data;
			});
		}
		submap.set(note.getPitchLocation().serialize(), note);
	}

	function removeNote(note: Note) {
		const submap: SharedMap = (fluidSequence as SharedMap).get(note.instrument.serialize()) as SharedMap;
		submap.delete(note.getPitchLocation().serialize());
	}

	return (
		<>
			<Head>
				<title>Sequencer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<TopBar
				key={updateSeq}
				currentInstrument={currentInstrument}
				sequence={seqData}
				setStepLength={(newStepLength) => {
					setStepLength(newStepLength);
				}}
				setBPM={(newBPM) => {
					let newSeqData = new SequenceMetadata(seqData);
					newSeqData.bpm = newBPM;
					setSeq(newSeqData);
				}}
				saveSequence={() => {
					const noteArr = getArray();
					Promise.all([
						EditSequence(seqData.id, seqData),
						ClearNotes(seqData.id),
					]).then((value) => {
						AddNotes(seqData.id, noteArr).then((value) =>
							alert("Saved Successfully")
						);
					});
				}}
				downloadSequence={() => {
					const noteArr = getArray();
					WriteMidi(seqData, noteArr);
				}}
				playSequence={() => {
					PlaySequence(seqData, unsharedMap);
					setTickFunction(() => {
						setTick(getTick());
					});
				}}
				stopSequence={() => {
					StopSequence();
				}}
				setInstrument={(instrument) => {
					switch (instrument) {
						case "Piano":
							setCurrentInstrument({
								instrument: instrumentList.Piano,
								primary: "--yellow",
								accent: "--yellow-accent",
							});
							break;
						case "Guitar":
							setCurrentInstrument({
								instrument: instrumentList.Guitar,
								primary: "--green",
								accent: "--green-accent",
							});
							break;
						case "Bass":
							setCurrentInstrument({
								instrument: instrumentList.Bass,
								primary: "--blue",
								accent: "--blue-accent",
							});
							break;
						case "Trumpet":
							setCurrentInstrument({
								instrument: instrumentList.Trumpet,
								primary: "--red",
								accent: "--red-accent",
							});
							break;
						case "Synth Drum":
							setCurrentInstrument({
								instrument: instrumentList.Synth_Drum,
								primary: "--purple",
								accent: "--purple-accent",
							});
							break;
					}
				}}
				setTimeSig={(timeSig) => {
					let [num, den] = timeSig.split("/");
					parseInt(num);
					parseInt(den);
					let newSeqData = new SequenceMetadata(seqData);
					newSeqData.numerator = parseInt(num);
					newSeqData.denominator = parseInt(den);
					setSeq(newSeqData);
				}}
				setLength={(length) => {
					let newSeqData = new SequenceMetadata(seqData);
					newSeqData.length = parseInt(length);
					setSeq(newSeqData);
				}}
			/>
			<PianoRoll
				sequence={seqData}
				stepLength={stepLength}
				sequenceMap={unsharedMap}
				currentInstrument={currentInstrument}
				addNote={addNote}
				removeNote={removeNote}
				tick={tick}
			/>
			<Cursor
				addNote={addNote}
				removeNote={removeNote}
				noteMap={unsharedMap}
				sequence={seqData}
			/>
		</>
	);
}

export async function getServerSideProps({
	params,
}: GetServerSidePropsContext<PageParams>): Promise<
	GetServerSidePropsResult<ContentPageProps>
> {
	try {
		const databaseSequence = await GetSequence((params as PageParams).id);
		const databaseNotes = await GetNotes((params as PageParams).id);
		if (
			!(
				databaseNotes instanceof Array<Note> &&
				databaseSequence instanceof SequenceMetadata
			)
		) {
			throw new Error("Notes or Sequence not found");
		}

		return {
			// Passed to the page component as props
			props: {
				sequence: JSON.parse(JSON.stringify(databaseSequence)),
				notes: JSON.parse(JSON.stringify(databaseNotes)),
			},
		};
	} catch (e) {
		return {
			notFound: true,
		};
	}
}

function getOctave(note: Note) {
	const pitchNumber: number = note.pitch % 12;
	const octaveNumber: number = (note.pitch - pitchNumber) / 12;
	return octaveNumber;
}
