import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sequencer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{
        display: "flex",
        flexFlow: "row nowrap",
        alignItems: "center",
        justifyContent: "center",
        height: "100vh",
      }}>
        <p>nothing here (yet!)</p>
      </div>
    </>
  )
}
