import Head from 'next/head'
import TopBar from '@/components/TopBar'
import PianoRoll from '@/components/PianoRoll'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sequencer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TopBar />
      <PianoRoll />
    </>
  )
}
