import Head from "next/head";
import TopBar from "@/components/TopBar";
import PianoRoll from "@/components/PianoRoll";
import { AddSequence } from "@/database/calls";
import { SequenceMetadata } from "@/server/types";
import * as randomstring from "randomstring";
import { useRouter } from "next/router";
import {
	GetServerSideProps,
	GetServerSidePropsContext,
	GetServerSidePropsResult,
} from "next";
import { InsertOneResult } from "mongodb";

type route = {
	route: string;
};

export default function Home() {
	return (
		<>
			<Head>
				<title>Sequencer</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>Creating Sequence...</div>
		</>
	);
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
	const newSeq = new SequenceMetadata({
		id: randomstring.generate(),
		length: 32,
		bpm: 120,
		numerator: 4,
		denominator: 4,
	});

	const response = await AddSequence(newSeq);
	console.log(response);
	if (response !== undefined && response?.acknowledged) {
		return {
			redirect: {
				permanent: false,
				destination: `/sequencer/${newSeq.id}`,
			},
		};
	} else {
		return {
			redirect: {
				permanent: true,
				destination: "..",
			},
		};
	}
}
